name: Destroy Terraform

on:
  workflow_dispatch:   # 👈 run manually from GitHub Actions tab

env:
  AWS_REGION: "us-east-2"

permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        run: |
          cd ./terraform
          terraform init

      - name: Terraform Destroy
        run: |
          cd ./terraform
          terraform destroy -auto-approve
